name: Publish to Comfy Registry

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to Comfy Registry
        uses: Comfy-Org/publish-node-action@v1
        with:
          # Change this line specifically:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
